// In-Memory Data Store with Seed Data for Party App
export const partyData = {
  party: {
    id: "party_001",
    code: "FRIDAY_HIGH",
    name: "🎉 불금 하이파이브 네트워킹 파티",
    location: "강남 라운지 바 HIGH",
    description: "처음 만난 사람도 10분 만에 절친되는 초특급 아이스브레이킹 파티!",
    createdAt: new Date().toISOString(),
    status: "active",
  },
  host: {
    id: "host_001",
    name: "루카스 (Host 👑)",
    mbti: "ENFJ",
    bio: "오늘 밤 주인공은 여러분! 모두 친해질 때까지 집에 못 갑니다 🔥",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    tags: ["파티 기획자", "분위기 메이커", "와인 애호가", "ENFJ", "무한 긍정"],
  },
  guests: [
    {
      id: "guest_001",
      name: "이지우",
      mbti: "ENFP",
      age: "만 25세",
      height: "165cm",
      job: "UI/UX 디자이너",
      bio: "텐션 200%! 오늘 새로운 친구 10명 사귀는 게 목표예요 ✨",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80",
      drinkStyle: "소주 1.5병 / 하이볼",
      smoking: "비흡연",
      hobby: "보드게임, 맛집탐방",
      tags: ["만 25세", "165cm", "ENFP", "소주 1.5병", "비흡연", "보드게임 러버", "맛집 탐방"],
      icebreakerQuestion: "내가 요즘 제일 꽂혀있는 취미는?",
      icebreakerAnswer: "주말마다 새로운 디저트 카페 투어하기 🍰",
      completedMissions: ["quest_001"],
      points: 150,
      scannedGuests: ["guest_002", "guest_003"],
    },
    {
      id: "guest_002",
      name: "김민재",
      mbti: "INTJ",
      age: "만 28세",
      height: "182cm",
      job: "풀스택 개발자",
      bio: "겉은 조용하지만 친해지면 말 많아요! 테크와 운동 좋아합니다 💻",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
      drinkStyle: "수제맥주 2잔",
      smoking: "비흡연",
      hobby: "헬스, 테크/스타트업",
      tags: ["만 28세", "182cm", "INTJ", "맥주파", "비흡연", "헬스", "스타트업"],
      icebreakerQuestion: "가장 최근에 감명 깊게 본 영화나 책은?",
      icebreakerAnswer: "인터스텔라 (벌써 5번째 정주행 중 🚀)",
      completedMissions: ["quest_002"],
      points: 120,
      scannedGuests: ["guest_001"],
    },
    {
      id: "guest_003",
      name: "박서연",
      mbti: "ESFJ",
      age: "만 24세",
      height: "168cm",
      job: "마케터",
      bio: "어색한 분위기 절대 못 참는 파티 요정 🥂 다들 짠해요!",
      avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80",
      drinkStyle: "와인 / 샴페인",
      smoking: "비흡연",
      hobby: "필라테스, 사진 촬영",
      tags: ["만 24세", "168cm", "ESFJ", "와인/샴페인", "비흡연", "필라테스", "사진"],
      icebreakerQuestion: "인생에서 가장 잊을 수 없는 여행지는?",
      icebreakerAnswer: "작년 여름에 다녀온 스위스 인터라켄 패러글라이딩 🪂",
      completedMissions: ["quest_001", "quest_003"],
      points: 220,
      scannedGuests: ["guest_001", "guest_004"],
    },
    {
      id: "guest_004",
      name: "최도현",
      mbti: "INTP",
      age: "만 27세",
      height: "177cm",
      job: "음악 프로듀서",
      bio: "독특한 취향과 엉뚱한 대화 환영! 음악 추천해드릴게요 🎧",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
      drinkStyle: "칵테일 / 위스키",
      smoking: "흡연",
      hobby: "인디밴드 디깅, LP 수집",
      tags: ["만 27세", "177cm", "INTP", "위스키", "흡연", "인디음악", "LP수집"],
      icebreakerQuestion: "나의 인생 곡 Top 1은?",
      icebreakerAnswer: "검정치마의 'EVERYTHING' 🎶",
      completedMissions: [],
      points: 50,
      scannedGuests: [],
    },
    {
      id: "guest_005",
      name: "정하은",
      mbti: "ENTP",
      age: "만 26세",
      height: "170cm",
      job: "브랜드 매니저",
      bio: "흥미진진한 토론과 꿀잼 에피소드 부자 ⚡ 밤새 수다 떨 사람?",
      avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&auto=format&fit=crop&q=80",
      drinkStyle: "소맥 / 주당",
      smoking: "비흡연",
      hobby: "러닝, 미술관 도슨트",
      tags: ["만 26세", "170cm", "ENTP", "주당", "비흡연", "러닝크루", "전시회"],
      icebreakerQuestion: "내가 가진 의외의 특기나 징크스는?",
      icebreakerAnswer: "처음 만난 사람 3초 만에 관상(?) 맞추기 🔮",
      completedMissions: ["quest_001"],
      points: 100,
      scannedGuests: ["guest_002"],
    },
  ],
  missions: [
    {
      id: "quest_001",
      title: "MBTI 'E'인 사람 찾아 건배하기 🥂",
      category: "아이스브레이킹",
      description: "외향형(E) 성향의 게스트를 찾아 건배하고 QR을 스캔하세요!",
      reward: "시원한 하이볼 1잔 교환권 🍹",
      points: 100,
      badge: "인싸의 첫걸음",
      targetCount: 1,
      completedBy: ["guest_001", "guest_003", "guest_005"],
      isUrgent: false,
    },
    {
      id: "quest_002",
      title: "서로 다른 직군 게스트 3명 QR 스캔 📱",
      category: "네트워킹",
      description: "나와 다른 일을 하는 멋진 파티원 3명의 QR을 스캔하고 도감을 완성하세요.",
      reward: "파티 VIP 핑거푸드 플래터 🧀",
      points: 150,
      badge: "마당발 네트워커",
      targetCount: 3,
      completedBy: ["guest_002"],
      isUrgent: false,
    },
    {
      id: "quest_003",
      title: "호스트 루카스와 가위바위보 승리 👑",
      category: "호스트 챌린지",
      description: "호스트를 찾아가 가위바위보 대결에서 이기고 비밀 시크릿 코드를 받으세요!",
      reward: "프리미엄 샷 1잔 🥃",
      points: 80,
      badge: "승리의 파이터",
      targetCount: 1,
      completedBy: ["guest_003"],
      isUrgent: true,
    },
    {
      id: "quest_004",
      title: "공통 취미를 가진 소울메이트 찾기 🎯",
      category: "소울메이트",
      description: "프로필 태그 중 나와 같은 취미(운동, 음악, 맛집 등)를 가진 사람과 대화 나누기!",
      reward: "파티 스티커 팩 & 50P 🎁",
      points: 120,
      badge: "소울메이트 탐험가",
      targetCount: 1,
      completedBy: [],
      isUrgent: false,
    },
    {
      id: "quest_005",
      title: "롤링페이퍼에 따뜻한 응원 2개 남기기 💌",
      category: "훈훈 미션",
      description: "오늘 고마웠거나 호감 가는 파티원에게 롤링페이퍼 메시지를 남겨보세요.",
      reward: "디저트 교환권 🍰",
      points: 90,
      badge: "분위기 천사",
      targetCount: 2,
      completedBy: [],
      isUrgent: false,
    },
  ],
  rollingPapers: [
    {
      id: "rp_001",
      senderName: "도현",
      senderId: "guest_004",
      receiverId: "guest_001",
      receiverName: "이지우",
      message: "지우님 웃는 모습이 너무 매력적이세요! 파티 텐션 팍팍 올려주셔서 감사합니다 👍",
      color: "bg-pink-50 text-pink-900 border-pink-200",
      createdAt: "방금 전",
      isAnonymous: false,
    },
    {
      id: "rp_002",
      senderName: "익명의 요정 🧚",
      senderId: "anon",
      receiverId: "guest_002",
      receiverName: "김민재",
      message: "민재님 아까 개발이랑 헬스 이야기 나눌 때 눈빛이 초롱초롱하셨어요! 멋지십니다 ㅎㅎ",
      color: "bg-purple-50 text-purple-900 border-purple-200",
      createdAt: "5분 전",
      isAnonymous: true,
    },
    {
      id: "rp_003",
      senderName: "서연",
      senderId: "guest_003",
      receiverId: "all",
      receiverName: "파티원 전체 🎉",
      message: "오늘 다들 너무 잘 어울려주셔서 행복해요! 2차도 무조건 함께 가요 우리 🥂✨",
      color: "bg-amber-50 text-amber-900 border-amber-200",
      createdAt: "10분 전",
      isAnonymous: false,
    },
    {
      id: "rp_004",
      senderName: "하은",
      senderId: "guest_005",
      receiverId: "host_001",
      receiverName: "루카스 (Host)",
      message: "호스트님 파티 퀘스트 아이디어 최고예요! 어색할 틈이 1도 없네요 🔥",
      color: "bg-emerald-50 text-emerald-900 border-emerald-200",
      createdAt: "15분 전",
      isAnonymous: false,
    },
  ],
  popups: [
    {
      id: "popup_001",
      type: "general", // "general", "mission", "result"
      title: "🥂 호스트 루카스의 알림",
      message: "잠시 후 9시에 [자리 셔플 타임]이 진행됩니다! 지금 테이블과 마지막 짠~ 해주세요!",
      timestamp: new Date().toLocaleTimeString('ko-KR', { hour: '2-digit', minute: '2-digit' }),
      highlight: "새로운 인연을 만날 찬스!",
      actionText: "확인했습니다",
    },
    {
      id: "popup_002",
      type: "mission",
      title: "🚨 게릴라 미션 발동!",
      message: "지금부터 5분간! 나와 '생일 월'이 같은 게스트를 찾아 QR을 스캔하면 더블 포인트 획득!",
      timestamp: "20:45",
      highlight: "제한시간 5분 (보상 200P)",
      actionText: "미션 도전하기",
    },
    {
      id: "popup_003",
      type: "result",
      title: "🏆 [1차 퀘스트 결과 발표]",
      message: "가장 먼저 3명과 악수를 마친 1등 '박서연'님! 샴페인 1잔 쿠폰이 발급되었습니다 🎉",
      timestamp: "20:30",
      highlight: "1등 박서연님 축하드립니다!",
      actionText: "축하 박수 보내기",
    },
  ],
  rewards: [
    {
      id: "rew_001",
      guestId: "guest_001",
      title: "시원한 하이볼 1잔 교환권 🍹",
      questTitle: "MBTI 'E'인 사람 찾아 건배하기",
      code: "HIGH-7782",
      isUsed: false,
      issuedAt: "20:20",
    },
    {
      id: "rew_002",
      guestId: "guest_003",
      title: "프리미엄 샷 1잔 🥃",
      questTitle: "호스트 루카스와 가위바위보 승리",
      code: "SHOT-9914",
      isUsed: false,
      issuedAt: "20:35",
    },
  ]
};
